# Generated by Django 5.1.2 on 2024-10-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolznosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dol', models.CharField(default='Что-то сломалось', max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'А1. Должности',
            },
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Что-то сломалось', max_length=150, verbose_name='ФИО')),
                ('uda', models.CharField(default='Что-то сломалось', max_length=1, verbose_name='Увольнение')),
                ('dat', models.CharField(default='Что-то сломалось', max_length=11, verbose_name='Дата увольнения')),
                ('dol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hose.dolznosti')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Б1. Сотрудники (А1)',
            },
        ),
    ]
